app:
  auth:
    header-scheme-name: authorization
    token-type: Bearer
    aceess-secret: DeaguGreenArtAcademyClass502ForJavaSpringBoot
    accessTokenExpiry: 3600000 #86400000-1일 #3600000-60분
    refresh-secret: ForJavaSpringBootClass502DaeguGreenArtAcademy
    refreshTokenExpiry: 1296000000 #15일
    redis-access-black-key: "D-AT-BLACK"
    redis-refresh-key: "D-RT"
  oauth2:
    authorized-redirect-uris:
      #- http://localhost:8080/test.html
      - http://localhost:3000/oauth/redirect
      - http://localhost:8080/oauth/redirect
      - http://192.168.0.203:8080/oauth/redirect  #서윤 ip주소
      - http://192.168.0.47:3000/oauth/redirect   #동은님 아이피주소: 포트번호 ~/oauth/redirect-
      - http://112.222.157.156:5004/login/oauth2/code/kakao
      #- http://192.168.0.50:8080/oauth/redirect  #원희 ip주소
      #- http://192.168.0.203:8080/oauth/redirect #서윤 ip주소
mybatis:
  type-aliases-package: com.green.winey_final
  mapper-locations: mapper/**/*.xml

spring:
  mail:
    host: smtp.naver.com
    port: 465
    username: greenwiney@naver.com
    password: green502
    properties:
      debug: true
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://localhost:3306/finaltest?useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999 #jdbc-url: jdbc:mariadb://192.168.0.144:3306/team_d
    username: root
    password: green502
  jpa:
    hibernate:
      ddl-auto: update #update #create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_updates: true
        order_inserts: true
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 954740580062-id63sg5rs1o3fc86vttfobuaaqg9i6t2.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 837560757904353
            client-secret: 65f59cb20cf6ea8d968be48419097c88
            scope:
              - email
              - public_profile
          naver:
            client-id: kvhG2QHGdpArWfUlhmtT
            client-secret: FjqfF3UThc
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
          kakao:
            client-id: 63c2ccf48233929cf35206dbb6fcdb14
            client-secret: 2IMmPdp2Ngmd5AMBfMLtZf3gv2qWqww8
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            clientName: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# cors
cors:
  allowed-origins: 'http://localhost:8080'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

# swagger
springdoc:
  swagger-ui:
    path: /swagger.html

file:
  dir: D:/home/download

---

spring:
  config:
    activate:
      on-profile: "test"
  datasource:
    url: jdbc:mariadb://localhost:3306/finaltest


---
app:
  oauth2:
    authorized-redirect-uris:
      - http://192.168.0.144:5004/oauth/redirect
      - http://112.222.157.156:5004/login/oauth2/code/kakao

spring:
  config:
    activate:
      on-profile: "prod"
  data:
    redis:
      host: 192.168.0.144
  datasource:
    jdbc-url: jdbc:mariadb://192.168.0.144:3306/team_d?rewriteBatchedStatements=true
file:
  dir: /home/download
server:
  port: 8080

cors:
  allowed-origins: 'http://192.168.0.144:8080'


