app:
  auth:
    header-scheme-name: authorization
    token-type: Bearer
    aceess-secret: DeaguGreenArtAcademyClass502ForJavaSpringBoot
    accessTokenExpiry: 200000
    refresh-secret: ForJavaSpringBootClass502DaeguGreenArtAcademy
    refreshTokenExpiry: 1296000000
    redis-access-black-key: "Z-AT-BLACK"
    redis-refresh-key: "Z-RT"
  oauth2:
    authorized-redirect-uris:
      - http://localhost:8082/oauth/redirect
      - http://192.168.0.50:8082/oauth/redirect #원희 ip주소
mybatis:
  type-aliases-package: com.green.winey_final
  mapper-locations: mappers/**/*.xml

spring:
  thymeleaf:
    check-template-location: true
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    cache: false
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://localhost:3306/finaltest
    username: root
    password: green502
  jpa:
    hibernate:
      ddl-auto: update #update #create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 954740580062-id63sg5rs1o3fc86vttfobuaaqg9i6t2.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 837560757904353
            client-secret: 65f59cb20cf6ea8d968be48419097c88
            scope:
              - email
              - public_profile
          naver:
            client-id: kvhG2QHGdpArWfUlhmtT
            client-secret: FjqfF3UThc
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
          kakao:
            client-id: b3903efc9bf7d64c7f9cb73b64c265f0
            client-secret: vJzx3Vf8BnOhUm1vypGbDgYzgppjYEYG
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            clientName: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# cors
cors:
  allowed-origins: 'http://localhost:8082'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

# swagger
springdoc:
  swagger-ui:
    path: /swagger.html

file:
  dir: D:/home/download

server:
  port: 8082

---

spring:
  config:
    activate:
      on-profile: "test"
  datasource:
    url: jdbc:mariadb://localhost:3306/finaltest
file:
  dir: D:/home/download

---

spring:
  config:
    activate:
      on-profile: "prod"
  data:
    redis:
      host: 192.168.0.144
  datasource:
    url: jdbc:mariadb://192.168.0.144:3306/team_d
file:
  dir: /home/download
server:
  port: 8080



